export const SAVE_SEARCH_GIF_RESULTS = 'SAVE_SEARCH_GIF_RESULTS';
export const APPEND_SEARCH_GIF_RESULTS = 'APPEND_SEARCH_GIF_RESULTS';
export const UPDATE_API = 'UPDATE_API';
export const INCREMENT_API_OFFSET = 'INCREMENT_API_OFFSET';
